version: "3.8"

services:
  bookstore-api-gateway-service:
    image: bookstore-api-gateway-service:v1.0
    container_name: bookstore-api-gateway-service
    build:
      context: ./bookstore-api-gateway-service
      dockerfile: Dockerfile
    ports:
      - "8765:8765"  # Exposing Zuul Gateway
    networks:
      - bookstore-network
    environment:
      - SERVER_PORT=8765
      - SPRING_PROFILES_ACTIVE=docker

  bookstore-account-service:
    image: bookstore-account-service:v1.0
    container_name: bookstore-account-service
    build:
      context: ./bookstore-account-service
      dockerfile: Dockerfile
    ports:
      - "4001:4001"  # Exposing Account Service
    networks:
      - bookstore-network
    environment:
      - SERVER_PORT=4001
      - SPRING_PROFILES_ACTIVE=local

  bookstore-billing-service:
    image: bookstore-billing-service:v1.0
    container_name: bookstore-billing-service
    build:
      context: ./bookstore-billing-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"  # Exposing Billing Service
    networks:
      - bookstore-network
    environment:
      - SERVER_PORT=5001
      - SPRING_PROFILES_ACTIVE=local 

  bookstore-catalog-service:
    image: bookstore-catalog-service:v1.0
    container_name: bookstore-catalog-service
    build:
      context: ./bookstore-catalog-service
      dockerfile: Dockerfile
    ports:
      - "6001:6001"  # Exposing Catalog Service
    networks:
      - bookstore-network
    environment:
      - SERVER_PORT=6001
      - SPRING_PROFILES_ACTIVE=local

  bookstore-order-service:
    image: bookstore-order-service:v1.0
    container_name: bookstore-order-service
    build:
      context: ./bookstore-order-service
      dockerfile: Dockerfile
    ports:
      - "7001:7001"  # Exposing Order Service
    networks:
      - bookstore-network
    environment:
      - SERVER_PORT=7001
      - SPRING_PROFILES_ACTIVE=local

  bookstore-payment-service:
    image: bookstore-payment-service:v1.0
    container_name: bookstore-payment-service
    build:
      context: ./bookstore-payment-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"  # Exposing Payment Service
    networks:
      - bookstore-network
    environment:
      - SERVER_PORT=8001
      - SPRING_PROFILES_ACTIVE=local    

networks:
  bookstore-network:
    driver: bridge